//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VPN Client.rc
//
#define IDOK2                           3
#define IDCANCEL2                       4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUT                       101
#define IDD_VPNCLIENT_DIALOG            102
#define IDS_TOOLTIP_TEST                102
#define IDS_USE_LOGIN_ACCOUNT           102
#define IDS_SET_LOGIN_ACCOUNT           103
#define IDD_HOSTINFODIALOG              104
#define IDS_VERSION_FORMAT              104
#define IDS_CREATE_NETWORK              105
#define IDS_JOIN_NETWORK                106
#define IDS_NETWORK_ID                  107
#define IDS_NETWORK_PASSWORD            108
#define IDS_NETWORK_TYPE                109
#define IDS_SUBGROUP                    109
#define IDS_OK                          110
#define IDS_CANCEL                      111
#define IDS_INVITE                      112
#define IDS_EXIT                        113
#define IDS_LOGIN                       114
#define IDS_LOGOUT                      115
#define IDS_CREATE                      116
#define IDS_JOIN                        117
#define IDS_ACCOUNT                     118
#define IDS_PASSWORD                    119
#define IDS_START                       120
#define IDS_TURNOFF                     121
#define IDS_NEXT                        122
#define IDS_REMOVE                      123
#define IDS_CLOSE                       124
#define IDS_USE                         125
#define IDS_TYPE                        126
#define IDS_NETWORK_ADM                 127
#define IDR_MAINFRAME                   128
#define IDS_ACTIVATE                    128
#define IDD_CREATE_SUBNET               129
#define IDS_DEACTIVATE                  129
#define IDD_JOIN_SUBNET                 130
#define IDS_ACTIVE                      130
#define IDD_DIALOG1                     131
#define IDD_CHAT                        131
#define IDS_DEACTIVE                    131
#define IDB_TREE_CLOSED                 132
#define IDB_TREE_OPENED                 133
#define IDR_MAINMENU                    134
#define IDD_DLGFILETRANS                135
#define IDI_ICON1                       140
#define IDS_COLON                       140
#define IDI_ICON2                       141
#define IDI_ICON3                       142
#define IDI_ICON4                       143
#define IDS_SERVER_NEWS                 145
#define IDS_DONT_SHOW                   146
#define IDD_INFO                        159
#define IDD_SETUP                       160
#define IDS_SETTINGS                    160
#define IDS_BASIC                       161
#define IDS_BANDWIDTH                   162
#define IDR_INF_FILE                    164
#define IDR_DRIVER32                    165
#define IDR_RCDATA1                     166
#define IDS_GUI_LANG                    166
#define IDI_SETUP                       167
#define IDS_LOCAL_NAME                  167
#define IDS_UDP_TUNNEL_ADDRESS          168
#define IDS_AUTOSTART                   169
#define IDB_BITMAP1                     170
#define IDS_RECONNECT                   170
#define IDD_DEBUG_TOOL                  171
#define IDS_AUTOUPDATE                  171
#define IDD_DLG_SETTINGS                172
#define IDS_AUTO_SETFW                  172
#define IDD_ID_LOGIN                    173
#define IDS_KT_TIME                     173
#define IDR_DRIVER64                    175
#define IDR_DEVINS32                    176
#define IDR_DEVINS64                    177
#define IDR_DRIVER64D                   179
#define IDR_DRIVER32D                   180
#define IDI_BASIC                       181
#define IDI_BANDWIDTH                   182
#define IDD_SETTING_BASIC               183
#define IDD_SETTING_BANDWIDTH           184
#define IDS_MAX_INGOING                 185
#define IDS_MAX_OUTGOING                186
#define IDB_EVA                         191
#define IDD_NET_MANAGE                  192
#define IDD_NETWORK_MANAGE              192
#define IDD_RESET_NETWORK               193
#define IDI_ICON4L                      194
#define IDI_ICON6                       195
#define IDI_ICON1L                      195
#define IDD_TUNNEL_PATH                 196
#define IDD_SERVER_MSG                  197
#define IDR_LAN_CHT                     199
#define IDR_CAT_X32                     202
#define IDR_CAT_X32D                    203
#define IDR_CAT_X64                     204
#define IDR_CAT_X64D                    205
#define IDR_LAN_CHS                     208
#define IDR_NTOOL                       209
#define IDB_CLOUD                       210
#define IDR_INF_FILE_N6                 211
#define IDR_DRIVER32_N6                 212
#define IDR_DRIVER64_N6                 213
#define IDR_CAT_X64N6                   214
#define IDR_CAT_X32N6                   215
#define IDD_PING_HOST                   216
#define IDD_HOST_PICKER                 217
#define IDD_VNET_GROUP                  218
#define IDB_GROUP                       219
#define IDD_GROUP_MANAGE                220
#define IDB_GROUP2                      223
#define IDD_NETWORK_OPTION              224
#define IDS_NETWORK_MANAGEMENT          250
#define IDS_GLOBAL_LOCK                 251
#define IDS_DISALLOW_NEW_USER           252
#define IDS_DISALLOW_DESC               253
#define IDS_VALIDATE_PASSWORD           255
#define IDS_RESET_PASSWORD              256
#define IDS_RELAY_HOST                  257
#define IDS_ALLOW_RELAY                 258
#define IDS_NO_RH                       259
#define IDS_RESET_ID_PASSWORD           260
#define IDS_MEMBER_INFO                 261
#define IDS_LAST_ONLINE_IP              262
#define IDS_LAST_ONLINE_TIME            263
#define IDS_STATUS                      264
#define IDS_TUNNEL_PATH                 280
#define IDS_NODE                        281
#define IDS_NETWORK_GROUP               282
#define IDS_P2P                         283
#define IDS_RELAY                       284
#define IDS_NMATRIX_SERVER              285
#define IDS_HUB_CLIENT                  290
#define IDS_SPOKE_CLIENT                291
#define IDS_HOST_INFO                   300
#define IDS_HOST_NAME                   301
#define IDS_VIRTUAL_IP                  302
#define IDS_TUNNEL_ADDRESS              303
#define IDS_DATA_IN                     304
#define IDS_DATA_OUT                    305
#define IDS_NO_DATA                     307
#define IDS_QUERYING                    308
#define IDS_QUERY                       308
#define IDS_OFFLINE                     400
#define IDS_NO_CONNECTION               401
#define IDS_NO_TUNNEL                   402
#define IDS_TRYING_TPT                  403
#define IDS_RELAYED_TUNNEL              404
#define IDS_DIRECT_TUNNEL               405
#define IDS_CONNECTING                  406
#define IDS_ONLINE                      407
#define IDS_STRING128                   410
#define IDS_GO_ONLINE                   410
#define IDS_GO_OFFLINE                  411
#define IDS_LEAVE_NETWORK               412
#define IDS_DELETE_NETWORK              413
#define IDS_MANAGE                      414
#define IDS_SET_SPOKE                   415
#define IDS_SET_HUB                     416
#define IDS_SET_RELAY                   417
#define IDS_CANCEL_RELAY                418
#define IDS_EVICT                       419
#define IDS_PING_HOST                   420
#define IDS_SEND_MESSAGE                421
#define IDS_COPY_ADDRESS                422
#define IDS_WIN_REMOTE_DESKTOP          423
#define IDS_EXPLORE_HOST                424
#define IDS_APPMODE                     425
#define IDS_SERVICEMODE                 426
#define IDS_INVITE_GROUPCHAT            427
#define IDS_SELECT_MEMBERS              428
#define IDS_GROUP_MSG                   429
#define IDS_CREATE_SUBGROUP             435
#define IDS_DELETE_SUBGROUP             436
#define IDS_RENAME                      437
#define IDS_SET_DEFAULT_SUBGROUP        438
#define IDS_MOVE_TO                     439
#define IDS_SUBGROUP_NAME               440
#define IDS_SUBGROUP_SETTING            441
#define IDS_DISABLE_SUBGROUP            442
#define IDS_DEFAULT_GROUP               443
#define IDS_STRING450                   450
#define IDS_STRING451                   451
#define IDS_STRING452                   452
#define IDS_STRING453                   453
#define IDS_STRING454                   454
#define IDS_STRING455                   455
#define IDS_STRING456                   456
#define IDS_STRING457                   457
#define IDS_STRING458                   458
#define IDS_STRING459                   459
#define IDS_STRING460                   460
#define IDS_STRING461                   461
#define IDS_UNKNOW_ERROR                500
#define IDS_NO_VNET                     501
#define IDS_PASSWORD_ERROR              502
#define IDS_HAS_JOINED                  503
#define IDS_LOCKED_VNET                 504
#define IDS_VNET_ID_EXISTED             505
#define IDS_STRING_LEN_ERROR            506
#define IDS_INPUT_VNET_ID               507
#define IDS_MAX_VNET_ID_LEN             508
#define IDS_INPUT_PASSWORD              509
#define IDS_MAX_PASSWORD_LEN            510
#define IDS_SERVER_NO_RESPONSE          511
#define IDC_LOGIN                       1000
#define IDC_NETNAME                     1005
#define IDC_PASSWORD                    1006
#define IDC_CREATE_SUBNET               1007
#define IDC_JOIN_SUBNET                 1008
#define IDC_NET_TREE                    1009
#define IDC_EDIT1                       1010
#define IDC_REGID                       1010
#define IDC_UDP_PORT                    1010
#define IDC_EDIT                        1010
#define IDC_GROUP_NAME                  1010
#define IDC_EDIT2                       1011
#define IDC_HISTORY                     1011
#define IDC_OUTGOING_RATE               1011
#define IDC_KT_TIME                     1011
#define IDC_CHAT                        1012
#define IDC_SEND                        1012
#define IDC_VIP                         1014
#define IDC_VIP2                        1015
#define IDC_HOSTNAME                    1016
#define IDC_TUNNEL_IP                   1019
#define IDC_DATA_IN                     1020
#define IDC_DATA_OUT                    1021
#define IDC_RICHEDIT21                  1022
#define IDC_CHAT_EDIT                   1023
#define ID_NEXT                         1026
#define IDC_MSG                         1027
#define IDC_TITLE                       1028
#define IDC_INFO                        1029
#define IDC_VERSION                     1030
#define IDC_SET_REGID                   1031
#define IDC_GET_REGID                   1032
#define IDC_RESET_ADAPTER               1033
#define IDC_RENEW_ADAPTER               1034
#define IDC_STOP_SERVICE                1035
#define IDC_START_SERVICE               1036
#define IDC_INSTALL_SERVICE             1037
#define IDC_DELETE_SERVICE              1038
#define IDC_SHOW_CONSOLE                1039
#define IDC_CLOSE_PIPE                  1040
#define IDC_LIST_CATEGORY               1040
#define IDC_CREATE_PIPE                 1041
#define IDC_START_LISTEN                1042
#define IDC_PRINT_CONN_NAME             1043
#define IDC_LOGIN_NAME                  1044
#define IDC_LOGIN_PASSWORD              1045
#define IDC_DEBUG                       1046
#define IDC_READ                        1047
#define IDC_WRITE                       1048
#define IDC_USER_MODE                   1049
#define IDC_KERNEL_MODE                 1050
#define IDC_CHECK_UMRB                  1051
#define IDC_CHECK1                      1052
#define IDC_CHECK_AUTO_SETFW            1052
#define IDC_CLOSE_MSG                   1052
#define IDC_ALLOW_RELAY                 1052
#define IDC_NDIS6                       1052
#define IDC_DEF_OFFLINE                 1052
#define IDC_CHECK2                      1053
#define IDC_CHECK_AUTOSTART             1053
#define IDC_CHECK3                      1054
#define IDC_CHECK_RECONNECT             1054
#define IDC_CHECK4                      1055
#define IDC_CHECK_AUTOUPDATE            1055
#define IDC_INGOING_RATE                1056
#define IDC_SPIN_DATAIN                 1057
#define IDC_SPIN_DATAOUT                1058
#define IDC_D3DVIEW                     1058
#define IDC_BUTTON1                     1059
#define IDC_RESET_PASSWORD              1059
#define IDC_COPY_ERR                    1059
#define IDC_QUERY_TIME                  1059
#define IDC_SELECT_ALL                  1059
#define IDC_RENAME                      1059
#define IDC_NETWORK_PASSWORD            1060
#define IDC_REMOVE_ALL                  1060
#define IDC_DEFAULT_NETWORK_NAME        1061
#define IDC_DISALLOW_USER               1063
#define IDC_NEED_PASSWORD               1064
#define IDC_NETWORK_TYPE                1065
#define IDC_REMOVE_RELAY_HOST           1066
#define IDC_GROUP_RH                    1067
#define IDC_RELAY_HOST                  1068
#define IDC_PATH_LIST                   1069
#define IDC_LAST_ONLINE                 1070
#define IDC_UDP_TUNNEL_IP               1073
#define IDC_COMBO1                      1074
#define IDC_COMBO                       1074
#define IDC_TYPE_COMBO                  1074
#define IDC_NETWORK_ID                  1075
#define IDC_ACCOUNT                     1076
#define IDC_TYPE                        1077
#define IDC_GROUP                       1078
#define IDC_GUI_LANG                    1079
#define IDC_TUNNELADDRESS               1080
#define IDC_MAX_INGOING                 1081
#define IDC_MAX_OUTGOING                1082
#define IDC_DISALLOW_DESC               1083
#define IDC_GLOBAL_LOCK                 1084
#define IDC_S_NETWORK_ID                1085
#define IDC_S_NETWORK_PASSWORD          1086
#define IDC_S_HOST_NAME                 1087
#define IDC_S_VIRTUAL_IP                1088
#define IDC_S_TUNNEL_ADDRESS            1089
#define IDC_S_DATA_IN                   1090
#define IDC_S_DATA_OUT                  1091
#define IDC_S_HOSTNAME                  1092
#define IDC_S_KT_TIME                   1093
#define IDC_TREE                        1095
#define IDC_USER_LIST                   1096
#define IDC_INFO_LIST                   1097
#define IDC_QUERY_MEMBERS               1098
#define IDC_ACT                         1099
#define IDC_S_GROUP_NAME                1099
#define IDC_S_OPTION                    1100
#define IDS_STRING1500                  1500
#define IDS_STRING1501                  1501
#define IDS_STRING1502                  1502
#define IDS_STRING1503                  1503
#define IDS_STRING1504                  1504
#define IDS_STRING1505                  1505
#define IDS_STRING1506                  1506
#define IDS_STRING1507                  1507
#define IDS_STRING1508                  1508
#define IDS_STRING1509                  1509
#define IDS_STRING1510                  1510
#define IDS_STRING1511                  1511
#define IDS_STRING1512                  1512
#define ID_SYSTEM_SETTING               32771
#define ID_NETWORK_CREATENETWORK        32772
#define ID_NETWORK_JOINNETWORK          32773
#define ID_ABOUT_ABOUT                  32774
#define ID_HELP_CHECKUPDATE             32775
#define ID_SYSTEM_EXIT                  32776
#define ID_HELP_ABOUT                   32777
#define ID_Menu                         32778
#define ID_HELP_WEBSITE                 32779
#define ID_HELP_UNINSTALLADAPTERDRIVER  32781
#define ID_SYSTEM_SETTINGS              32782
#define ID_SYSTEM_SETLOGINACCOUNT       32783
#define ID_HELP_SERVERNEWS              32785
#define ID_32786                        32786
#define ID_32787                        32787
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_32790                        32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_32793                        32793
#define ID_32794                        32794
#define ID_32795                        32795
#define ID_32796                        32796
#define ID_453_456                      32807
#define ID_SWITCH_NETWORK_LOCATION      32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           136
#endif
#endif
